import type Database from 'better-sqlite3';
import { config } from './config.js';
import { db as defaultDb } from './db.js';
import { createBufferPost } from './publisher.js';
import { campaignPrompts } from './content-prompts.js';
import { campaignTypes, type Campaign, type CampaignType, type GeneratedContent, type GeneratedDraft } from './content-types.js';
import { deepSeekCompletion, type Completion } from './deepseek.js';
import { getJobStatistics, type JobStatistics } from './statistics.js';

const now = () => new Date().toISOString();
const weights = () => Object.fromEntries(config.content.defaultWeights.split(',').map(entry => { const [type,value] = entry.split(':'); return [type, Number(value) || 1]; }));
const slugify = (value:string) => value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
const escapeHtml = (value:string) => value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const markdownHtml = (value:string) => value.split(/\n\n+/).map(p => `<p>${escapeHtml(p).replace(/\n/g,'<br>')}</p>`).join('\n');
export function selectWeightedCampaign(campaigns: Campaign[], random = Math.random): Campaign | undefined {
  const eligible = campaigns.filter(c => c.enabled && c.weight > 0); const total = eligible.reduce((sum,c) => sum + c.weight,0);
  let point = random() * total; return eligible.find(c => (point -= c.weight) < 0) ?? eligible.at(-1);
}
export function choosePublicationKind(contentRatio:number, random = Math.random): 'JOB'|'CONTENT' { return random() < contentRatio ? 'CONTENT' : 'JOB'; }

export class ContentService {
  constructor(private database:Database.Database = defaultDb, private complete:Completion = deepSeekCompletion, private random = Math.random) { this.seedCampaigns(); }
  private seedCampaigns() { const statement=this.database.prepare(`INSERT INTO content_campaigns(type,name,prompt,enabled,weight,cooldown_days,created_at,updated_at) VALUES(?,?,?,1,?, ?,?,?) ON CONFLICT(type,name) DO NOTHING`); const configured=weights(); this.database.transaction(() => campaignTypes.forEach(type => statement.run(type,type.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()),campaignPrompts[type],configured[type] ?? 1,type === 'WEEKLY_DIGEST' ? 7 : 2,now(),now())))(); }
  listCampaigns():Campaign[] { return (this.database.prepare(`SELECT * FROM content_campaigns ORDER BY type`).all() as any[]).map(row=>({id:row.id,type:row.type,name:row.name,prompt:row.prompt,enabled:Boolean(row.enabled),weight:row.weight,cooldownDays:row.cooldown_days})); }
  statistics():JobStatistics { return getJobStatistics(this.database); }
  eligibleCampaigns(at = new Date()):Campaign[] { return this.listCampaigns().filter(c => !(this.database.prepare(`SELECT 1 FROM generated_content WHERE campaign_id=? AND status='published' AND published_at > ? LIMIT 1`).get(c.id,new Date(at.getTime()-c.cooldownDays*86_400_000).toISOString()))); }
  selectCampaign(at = new Date()) { return selectWeightedCampaign(this.eligibleCampaigns(at),this.random); }
  buildPrompt(campaign:Campaign, stats=this.statistics()) { return `You are AIJolt, an independent AI careers media.\n${campaign.prompt}\nEvery output must teach something, reveal a hiring trend, explain the AI job market, or show a concrete AIJolt advantage. Never produce generic motivational content. Use only supplied facts.\nFacts (JSON): ${JSON.stringify(campaign.type === 'BRAND' ? {capabilities:['verified AI job aggregation','job scoring','career intelligence']} : stats)}\nReturn valid JSON only with: title, excerpt (max 160 characters), socialText (max 260 characters), markdown (400-1200 words), seoTitle (max 60 characters), seoDescription (max 160 characters).`; }
  async generate(type?:CampaignType):Promise<GeneratedContent> { const campaign=type ? this.listCampaigns().find(c=>c.type===type&&c.enabled) : this.selectCampaign(); if(!campaign) throw new Error('No eligible content campaign'); const raw=await this.complete(this.buildPrompt(campaign)); let parsed:any; try { parsed=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,'')); } catch { throw new Error('DeepSeek returned invalid campaign JSON'); } for(const key of ['title','excerpt','socialText','markdown','seoTitle','seoDescription']) if(typeof parsed[key] !== 'string' || !parsed[key].trim()) throw new Error(`DeepSeek response is missing ${key}`); const base=slugify(parsed.title)||campaign.type.toLowerCase(); let slug=base; let suffix=2; while(this.database.prepare(`SELECT 1 FROM generated_content WHERE slug=?`).get(slug)) slug=`${base}-${suffix++}`; const draft:GeneratedDraft={title:parsed.title.trim(),slug,excerpt:parsed.excerpt.trim(),text:parsed.socialText.trim().slice(0,260),markdown:parsed.markdown.trim(),html:markdownHtml(parsed.markdown.trim()),seoTitle:parsed.seoTitle.trim(),seoDescription:parsed.seoDescription.trim(),image:'/images/article-placeholder.png'}; const info=this.database.prepare(`INSERT INTO generated_content(campaign_id,title,slug,excerpt,text,markdown,html,seo_title,seo_description,image,status,created_at) VALUES(@campaignId,@title,@slug,@excerpt,@text,@markdown,@html,@seoTitle,@seoDescription,@image,'draft',@createdAt)`).run({...draft,campaignId:campaign.id,createdAt:now()}); return this.getById(Number(info.lastInsertRowid))!; }
  history():GeneratedContent[] { return (this.database.prepare(`SELECT g.*,c.type FROM generated_content g JOIN content_campaigns c ON c.id=g.campaign_id ORDER BY g.created_at DESC`).all() as any[]).map(this.map); }
  private map=(row:any):GeneratedContent=>({id:row.id,campaignId:row.campaign_id,type:row.type,title:row.title,slug:row.slug,excerpt:row.excerpt,text:row.text,markdown:row.markdown,html:row.html,seoTitle:row.seo_title,seoDescription:row.seo_description,image:row.image,status:row.status,providerId:row.provider_id,publishedAt:row.published_at,createdAt:row.created_at});
  getById(id:number) { const row=this.database.prepare(`SELECT g.*,c.type FROM generated_content g JOIN content_campaigns c ON c.id=g.campaign_id WHERE g.id=?`).get(id); return row ? this.map(row) : undefined; }
  async publish(id?:number,dry=config.dryRun):Promise<GeneratedContent> { const content=id ? this.getById(id) : this.history().find(item=>item.status==='draft'); if(!content) throw new Error('No draft content available'); if(this.database.prepare(`SELECT 1 FROM generated_content WHERE text=? AND status='published' AND id<>?`).get(content.text,content.id)) throw new Error('Identical content was already published'); if(dry) return content; if(!config.buffer.x) throw new Error('BUFFER_X_CHANNEL_ID is missing'); try { const post=await createBufferPost(content.text,config.buffer.x); this.database.prepare(`UPDATE generated_content SET status='published',provider_id=?,published_at=? WHERE id=?`).run(post.id,now(),content.id); } catch(error) { this.database.prepare(`UPDATE generated_content SET status='failed',error=? WHERE id=?`).run(error instanceof Error?error.message:String(error),content.id); throw error; } return this.getById(content.id)!; }
}
