import { config } from './config.js'; import { greenhouse } from './collectors/greenhouse.js'; import { lever } from './collectors/lever.js'; import { ashby } from './collectors/ashby.js';
import { normalize } from './normalize.js'; import { analyzeAI } from './ai.js'; import { upsert, db, rowToJob } from './db.js'; import { score } from './scoring.js'; import { logger } from './logger.js'; import { publish } from './publisher.js';
export async function collect() {
  const run = db.prepare(`INSERT INTO runs(kind,status,started_at) VALUES('collect','running',?)`).run(new Date().toISOString()); let accepted = 0, errors = 0;
  const tasks = [ ...config.boards.greenhouse.map((id: string) => () => greenhouse(id)), ...config.boards.lever.map((id: string) => () => lever(id)), ...config.boards.ashby.map((id: string) => () => ashby(id)) ];
  for (const task of tasks) try { for (const raw of await task()) { const ai = analyzeAI(raw); if (!ai.relevant) continue; upsert(normalize(raw)); accepted++; } } catch (e) { errors++; logger.error(e instanceof Error ? e.message : String(e)); }
  db.prepare(`UPDATE runs SET status=?,details=?,finished_at=? WHERE id=?`).run(errors ? 'partial' : 'success', JSON.stringify({ accepted, errors }), new Date().toISOString(), run.lastInsertRowid); logger.info(`Collection complete: ${accepted} AI jobs, ${errors} errors`);
}
export function rescore() { const rows = db.prepare(`SELECT * FROM jobs WHERE status='active'`).all() as any[]; const update = db.prepare(`UPDATE jobs SET score=? WHERE source=? AND external_id=?`); db.transaction(() => rows.forEach(r => { const j = rowToJob(r); update.run(score(j), j.source, j.externalId); }))(); logger.info(`Scored ${rows.length} jobs`); }
export function cleanup() { const info = db.prepare(`UPDATE jobs SET status='expired', expires_at=? WHERE status='active' AND (last_seen_at < datetime('now','-30 days') OR (posted_at IS NOT NULL AND posted_at < datetime('now','-120 days')))` ).run(new Date().toISOString()); logger.info(`Expired ${info.changes} jobs`); }
export async function start() { await collect(); rescore(); await publish(); setInterval(() => collect().then(rescore), config.collectInterval * 60_000); setInterval(() => publish(), config.publishInterval * 60_000); logger.info('AIJolt scheduler started'); }
